#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
OUT_FILE="$DIST_DIR/project-handbook.md"

mkdir -p "$DIST_DIR"

{
  echo "# Project Handbook (generated)"
  echo
  echo "_This file is generated by scripts/custom_builder.sh_"
  echo
  for f in "$ROOT_DIR/README.md" "$ROOT_DIR/METHOD.md" "$ROOT_DIR/QUICKSTART.md"; do
    echo "\n---\n"
    cat "$f"
  done
} > "$OUT_FILE"

echo "Generated: $OUT_FILE"
